services:
  backend:
    build:
      context: .
    ports:
      - '8080:8080'

    environment:
      - "SPRING_DATASOURCE_URL=${MYSQL_DATABASE_URL}"
      - "SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}"
    
    command: mvn spring-boot:run
    restart: unless-stopped